version: '3.8'

services:
  line-provider:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Line Provider Service
      - DEBUG=true
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
