version: '3.8'

services:
  line-provider:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Line Provider Service
      - DEBUG=true
      - REDIS_URL=redis://127.0.0.1:6378/0
    depends_on:
      - redis-line
    network_mode: host

  redis-line:
    image: redis:6
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

